articles/config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  resources :articles, :only => [:index, :new, :create]

  resources :users

end

articles/app/models/article.rb
class Article < ActiveRecord::Base
validates :title, :presence => true
validates :body, :presence => true
belongs_to :user
end

articles/app/models/user.rb
class User < ActiveRecord::Base

has_many :articles

validates :name, :presence => true
validates :login, :presence => true,
 :length => { :minimum => 6 }

end

articles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

articles/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(published: true)
  end
def new
 @article = Article.new
 end
 def create
 @article = Article.new(article_params)
 if @article.save
 flash[:notice] = 'Article was successfully created.'
 redirect_to articles_path
 else
 render :action => "new"
 end
 end
  def article_params
    params.require(:article).permit(:body, :title, :user_id)
  end    
end

articles/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :name)
    end
end

articles/app/helpers/application_helper.rb
module ApplicationHelper
end

articles/app/helpers/articles_helper.rb
module ArticlesHelper
end

articles/app/helpers/users_helper.rb
module UsersHelper
end

articles/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<p id="notice"><%= notice %></p>
<table>
 <tr>
 <th>Title</th>
 <th>Contents</th>
 <th>Author</th>
 </tr>
<% @articles.each do |article| %> 
 <tr>
 <td><%= article.title %></td>
 <td><%= article.body %></td>
 <td><%= article.user.name %></td>
 </tr>
<% end %>
</table>
<br />
<%= link_to 'New Article', new_article_path %>

articles/app/views/articles/new.html.erb
<h1>Article</h1>
<%= form_for(@article) do |f| %>
 <% if @article.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@article.errors.count, "error") %> prohibited
this article from being saved:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class="field">
 <%= f.label :title %><br />
 <%= f.text_field :title %>
 </div>
 <div class="field">
 <%= f.label :body, "Contents" %><br />
 <%= f.text_field :body %>
 </div>
 <div class="field">
 <%= f.label :user_id, "Author" %><br />
 <%= f.collection_select :user_id, User.all, :id, :login %>
 </div>
 <div class="field">
 <%= f.check_box :published %>
 <%= f.label :published, "Publiczny?" %>
 </div>
 <div class="actions">
 <%= f.submit %>
 </div>
<% end %>
<%= link_to 'Back', articles_path %>

articles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

articles/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

articles/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

articles/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

articles/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

articles/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>